- hosts: web
  tasks:
  - name: "sync website"
    synchronize:
      src: site/
      dest: /var/www/example.com
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no